#!/usr/bin/env node
"use strict";var T="https://api.imaginepdf.com";function c(t){let e=process.env[t];return e&&e.trim()?e.trim():void 0}function g(){let t=c("IMAGINEPDF_API_KEY");if(t)return t;console.error(`ImaginePDF API key not configured.

Set it before launching Claude:
  export IMAGINEPDF_API_KEY=pc_live_...
  claude

Create a key in the ImaginePDF dashboard: Settings \u2192 API Keys.
`),process.exit(1)}function d(){return c("IMAGINEPDF_API_URL")??T}var u=require("node:fs/promises");async function a(t,e,r,n,s){let o=`${e}${n}`,i=await fetch(o,{method:r,headers:{"X-API-Key":t,"Content-Type":"application/json"},...s?{body:JSON.stringify(s)}:{}});return w(i)}async function l(t,e,r){let n=await fetch(`${e}${r}`,{method:"GET",headers:{"X-API-Key":t}}),s;try{s=await n.json()}catch{throw new Error(`API returned non-JSON response: HTTP ${n.status} ${n.statusText}`)}if(!n.ok){let o=s?.error?.message||`HTTP ${n.status}: ${n.statusText}`;throw new Error(o)}return s}async function m(t,e,r,n,s){let o=`${e}${n}`,i=await fetch(o,{method:r,headers:{"X-API-Key":t},body:s});return w(i)}async function w(t){let e;try{e=await t.json()}catch{throw new Error(`API returned non-JSON response: HTTP ${t.status} ${t.statusText}`)}if(!t.ok||e.error){let r=e.error?.message||`HTTP ${t.status}: ${t.statusText}`;throw new Error(r)}return e.data}async function h(t,e){let r=await fetch(t);if(!r.ok)throw new Error(`Failed to download file: HTTP ${r.status} ${r.statusText}`);let n=Buffer.from(await r.arrayBuffer());await(0,u.writeFile)(e,n)}function f(t,e){return{get:r=>a(t,e,"GET",r),getRaw:r=>l(t,e,r),post:(r,n)=>a(t,e,"POST",r,n),patch:(r,n)=>a(t,e,"PATCH",r,n),postForm:(r,n)=>m(t,e,"POST",r,n),download:h}}function p(t){if(!t||typeof t!="object"||Array.isArray(t))return t;let e={};for(let[r,n]of Object.entries(t)){if(typeof n=="string"&&n.startsWith("data:")){console.error(`[imaginepdf] dropping inline data: image for '${r}' \u2014 pass an assets:<id> ref (upload first)`);continue}e[r]=n}return e}async function I(){let[t,e]=process.argv.slice(2);(!t||!["generate","batch","batch-status","batch-download"].includes(t))&&(console.error("Usage: generate.cjs <generate|batch|batch-status|batch-download> '<json>'"),process.exit(1));let n=e?JSON.parse(e):{},s=f(g(),d());switch(t){case"generate":{if(!n.designId)throw new Error("designId is required");let o=await s.post(`/api/v1/designs/${encodeURIComponent(n.designId)}/generate`,{data:p(n.data||{})});console.log(JSON.stringify(o));break}case"batch":{if(!n.designId)throw new Error("designId is required");if(!Array.isArray(n.rows)||n.rows.length===0)throw new Error("rows must be a non-empty array of { variable_name: value } objects");let o=await s.post(`/api/v1/designs/${encodeURIComponent(n.designId)}/batch`,{rows:n.rows.map(p)});console.log(JSON.stringify(o));break}case"batch-status":{if(!n.jobId)throw new Error("jobId is required");let o=await s.get(`/api/v1/batches/${encodeURIComponent(n.jobId)}`);console.log(JSON.stringify(o));break}case"batch-download":{if(!n.jobId)throw new Error("jobId is required");let o=await s.get(`/api/v1/batches/${encodeURIComponent(n.jobId)}/download`);console.log(JSON.stringify(o));break}}}I().catch(t=>{console.error(JSON.stringify({error:t.message})),process.exit(1)});
